import { WorkshopSettings, Quote, FilamentSpool, ClosedSale, ClientRecord } from '../types';

export const defaultWorkshopSettings: WorkshopSettings = {
  energyCostPerHour: 0.08455, // Consumo médio: 0,095 kW * R$ 0,89/kWh = ~R$ 0,08455 por hora de impressão
  kwhCost: 0.89, // Tarifa média de energia: R$ 0,89 por kWh
  operatorHourlyRate: 35.0, // R$/hora técnica
  materials: [
    {
      id: 'mat-1',
      name: 'PLA Premium Preto',
      type: 'PLA',
      brand: 'Voolt3D / 3D Fila',
      spoolPrice: 99.9,
      spoolWeightGrams: 1000,
      color: '#1e293b',
    },
    {
      id: 'mat-2',
      name: 'PETG XT Branco',
      type: 'PETG',
      brand: 'Esun / Creality',
      spoolPrice: 115.0,
      spoolWeightGrams: 1000,
      color: '#f8fafc',
    },
    {
      id: 'mat-3',
      name: 'ABS Industrial Cinza',
      type: 'ABS',
      brand: 'Printalot',
      spoolPrice: 125.0,
      spoolWeightGrams: 1000,
      color: '#64748b',
    },
    {
      id: 'mat-4',
      name: 'TPU Flex 95A Laranja',
      type: 'TPU',
      brand: '3D Fila',
      spoolPrice: 149.0,
      spoolWeightGrams: 1000,
      color: '#f97316',
    },
    {
      id: 'mat-5',
      name: 'Resina Standard Cinza 405nm',
      type: 'Resina',
      brand: 'Elegoo Standard',
      spoolPrice: 160.0,
      spoolWeightGrams: 1000,
      color: '#94a3b8',
    },
  ],
  printers: [
    {
      id: 'print-a1-combo',
      name: 'Bambu Lab A1 Combo',
      powerWatts: 95, // Potência média: 0,095 kW (90W - 95W)
      purchaseCost: 4400,
      lifetimeHours: 4000,
      maintenancePerHour: 0.8,
    },
    {
      id: 'print-1',
      name: 'Bambu Lab P1S / X1C',
      powerWatts: 95,
      purchaseCost: 6200,
      lifetimeHours: 5000,
      maintenancePerHour: 0.9,
    },
    {
      id: 'print-2',
      name: 'Creality Ender 3 V3 KE',
      powerWatts: 95,
      purchaseCost: 2200,
      lifetimeHours: 3000,
      maintenancePerHour: 1.2,
    },
    {
      id: 'print-3',
      name: 'Elegoo Saturn 3 Ultra (Resina)',
      powerWatts: 90,
      purchaseCost: 4500,
      lifetimeHours: 2500,
      maintenancePerHour: 2.0,
    },
  ],
  company: {
    name: 'ConexLab 3D',
    slogan: 'Manufatura Aditiva, Prototipagem Rápida & Peças Técnicas',
    document: '',
    phone: '',
    email: 'contato@conexlab3d.com.br',
    address: '',
    instagram: '@conexlab3d',
    pixKey: '',
    pixKeyType: 'Chave' as any,
    paymentMethods: 'PIX (Chave Instantânea), Cartão de Crédito (em até 12x), Débito e Boleto Bancário',
    paymentConditions: '50% de sinal para início da produção e 50% na conclusão / entrega',
  },
};

export const defaultQuote: Quote = {
  id: 'quote-001',
  quoteNumber: 'ORC-2026-084',
  issueDate: new Date().toISOString().split('T')[0],
  validityDays: 15,
  client: {
    name: 'Eng. Roberto Albuquerque',
    companyName: 'Mecatec Soluções Industriais',
    document: '29.384.192/0001-05',
    phone: '(11) 99123-8877',
    email: 'roberto@mecatecind.com.br',
    address: 'Rua das Indústrias, 450 - Campinas, SP',
  },
  items: [
    {
      id: 'piece-1',
      name: 'Gabinete para Placa IoT com Fecho Magnético',
      description: 'Case bipartido com encaixes de precisão para montagem de sensor industrial e conectores frontais.',
      technology: 'FDM (Filamento)',
      materialName: 'PETG XT Branco',
      materialColor: '#f8fafc',
      layerHeight: '0.20mm (Resolução Balanceada)',
      infill: '25% Giroide (Alta rigidez)',
      finish: 'Natural sem pós-processo (Bordas chanfradas)',
      printerId: 'print-a1-combo',
      materialId: 'mat-2',
      materialType: 'PETG',
      customMaterialPrice: 115.0,
      customPrinterWatts: 95,
      weightGrams: 145,
      printTimeHours: 6,
      printTimeMinutes: 20,
      operatorMinutes: 25,
      additionalCosts: 12.0, // Imãs de neodímio embutidos e insertos de latão
      failureRiskPercent: 8,
      profitMarginPercent: 65,
      quantity: 2,
    },
    {
      id: 'piece-2',
      name: 'Engrenagem Cônica de Redução Z18',
      description: 'Peça técnica funcional para protótipo de esteira automatizada. Alta tenacidade mecânica.',
      technology: 'FDM (Filamento)',
      materialName: 'ABS Industrial Cinza',
      materialColor: '#64748b',
      layerHeight: '0.16mm (Superfície Lisa)',
      infill: '60% Tri-Hexagonal (Máxima resistência)',
      finish: 'Vapor de acetona leve / Acabamento liso',
      printerId: 'print-1',
      materialId: 'mat-3',
      weightGrams: 52,
      printTimeHours: 2,
      printTimeMinutes: 45,
      operatorMinutes: 20,
      additionalCosts: 5.0,
      failureRiskPercent: 10,
      profitMarginPercent: 70,
      quantity: 4,
    },
    {
      id: 'piece-3',
      name: 'Manípulo Ergonômico de Trava Rápida',
      description: 'Manípulo para fixação manual com rosca M6 metálica sobreinjetada.',
      technology: 'FDM (Filamento)',
      materialName: 'PLA Premium Preto',
      materialColor: '#1e293b',
      layerHeight: '0.20mm',
      infill: '35% Grade',
      finish: 'Limpeza e calibragem dimensional',
      printerId: 'print-2',
      materialId: 'mat-1',
      weightGrams: 38,
      printTimeHours: 1,
      printTimeMinutes: 50,
      operatorMinutes: 15,
      additionalCosts: 4.5,
      failureRiskPercent: 5,
      profitMarginPercent: 55,
      quantity: 3,
    },
  ],
  discountType: 'percentage',
  discountValue: 5,
  shippingCost: 35.0,
  shippingMethod: 'Sedex Correios (Rastreio em 24h úteis)',
  leadTime: '3 a 4 dias úteis após confirmação',
  paymentTerms: '50% na aprovação do pedido e 50% no envio com fotos das peças',
  notes: 'Peças inspecionadas dimensionalmente com paquímetro digital (tolerância ±0.15mm). Acompanha nota fiscal ou recibo comercial.',
  termsAndWarranty: 'Garantia de 30 dias contra falhas de adesão de camadas ou delaminação em uso nominal recomendado. Não submeter peças em PLA a temperaturas contínuas acima de 55°C.',
};

export const defaultFilamentSpools: FilamentSpool[] = [
  {
    id: 'spool-1',
    name: 'PLA Premium Preto Ônix',
    brand: 'Voolt3D',
    materialType: 'PLA',
    colorName: 'Preto Ônix',
    colorHex: '#1e293b',
    diameterMm: 1.75,
    initialWeightGrams: 1000,
    currentWeightGrams: 680,
    emptySpoolWeightGrams: 230,
    purchasePrice: 99.9,
    purchaseDate: '2026-08-20',
    location: 'Bambu AMS Slot 1',
    status: 'in_use',
    minStockAlertGrams: 150,
    batchNumber: 'V3D-2026-88',
    notes: 'Excelente aderência de camada. Temperatura bico 215°C / mesa 60°C.',
  },
  {
    id: 'spool-2',
    name: 'PETG XT Branco Neve',
    brand: 'eSun',
    materialType: 'PETG',
    colorName: 'Branco Neve',
    colorHex: '#f8fafc',
    diameterMm: 1.75,
    initialWeightGrams: 1000,
    currentWeightGrams: 850,
    emptySpoolWeightGrams: 215,
    purchasePrice: 115.0,
    purchaseDate: '2026-08-25',
    location: 'Bambu AMS Slot 2',
    status: 'in_use',
    minStockAlertGrams: 200,
    batchNumber: 'ESN-PETG-04',
    notes: 'Material para peças funcionais mecânicas e caixas de proteção.',
  },
  {
    id: 'spool-3',
    name: 'ABS Industrial Cinza Chumbo',
    brand: 'Printalot',
    materialType: 'ABS',
    colorName: 'Cinza Chumbo',
    colorHex: '#64748b',
    diameterMm: 1.75,
    initialWeightGrams: 1000,
    currentWeightGrams: 320,
    emptySpoolWeightGrams: 240,
    purchasePrice: 125.0,
    purchaseDate: '2026-08-10',
    location: 'Dry Box Principal #1',
    status: 'in_use',
    minStockAlertGrams: 150,
    batchNumber: 'PLT-ABS-91',
    notes: 'Armazenado com sílica gel ativa. Para uso em câmara fechada.',
  },
  {
    id: 'spool-4',
    name: 'TPU Flexível 95A Laranja Sunset',
    brand: '3D Fila',
    materialType: 'TPU',
    colorName: 'Laranja Fluorescente',
    colorHex: '#f97316',
    diameterMm: 1.75,
    initialWeightGrams: 500,
    currentWeightGrams: 110,
    emptySpoolWeightGrams: 180,
    purchasePrice: 149.0,
    purchaseDate: '2026-07-15',
    location: 'Dry Box Flexíveis',
    status: 'in_use',
    minStockAlertGrams: 120,
    batchNumber: '3DF-TPU-12',
    notes: 'Estoque baixo! Restando poucas peças de vedação / dampers.',
  },
  {
    id: 'spool-5',
    name: 'Bambu PLA Basic Vermelho Fogo',
    brand: 'Bambu Lab',
    materialType: 'PLA',
    colorName: 'Vermelho Fogo',
    colorHex: '#ef4444',
    diameterMm: 1.75,
    initialWeightGrams: 1000,
    currentWeightGrams: 1000,
    emptySpoolWeightGrams: 195,
    purchasePrice: 119.0,
    purchaseDate: '2026-09-02',
    location: 'Armário de Estoque - Prateleira A',
    status: 'sealed',
    minStockAlertGrams: 150,
    batchNumber: 'BL-PLA-0992',
    notes: 'Carretel lacrado a vácuo com etiqueta RFID original.',
  },
  {
    id: 'spool-6',
    name: 'Resina Standard 405nm Cinza',
    brand: 'Elegoo',
    materialType: 'Resina',
    colorName: 'Cinza Fotopolímero',
    colorHex: '#94a3b8',
    diameterMm: 0,
    initialWeightGrams: 1000,
    currentWeightGrams: 450,
    emptySpoolWeightGrams: 90,
    purchasePrice: 160.0,
    purchaseDate: '2026-08-18',
    location: 'Bancada MSLA Saturn',
    status: 'in_use',
    minStockAlertGrams: 200,
    batchNumber: 'ELG-RES-88',
    notes: 'Para miniaturas e protótipos de alta definição milimétrica.',
  },
];

export const defaultClosedSales: ClosedSale[] = [
  {
    id: 'sale-001',
    quoteNumber: 'ORC-2026-081',
    closedDate: '2026-09-12',
    clientName: 'Dr. Lucas Medeiros - OdontoTech',
    clientPhone: '(11) 98765-4321',
    clientEmail: 'lucas@odontotech.com.br',
    totalPieces: 6,
    items: [
      {
        name: 'Guia Cirúrgico Prototipado & Suporte de Turbina',
        quantity: 6,
        technology: 'MSLA / SLA (Resina)',
        materialName: 'Resina Standard Cinza 405nm',
        materialType: 'Resina',
        weightGrams: 35,
        unitPrice: 75.0,
        totalPrice: 450.0,
        rawCost: 112.5,
        netProfit: 337.5,
      },
    ],
    subtotal: 450.0,
    discountAmount: 20.0,
    shippingCost: 28.0,
    finalTotal: 458.0,
    productionCost: 112.5,
    netProfit: 317.5,
    profitMarginPercent: 69.3,
    paymentMethod: 'PIX (Chave Instantânea)',
    status: 'delivered',
    notes: 'Cliente muito satisfeito com a precisão dos encaixes. Pediu orçamento para o próximo mês.',
    filamentDeducted: true,
  },
  {
    id: 'sale-002',
    quoteNumber: 'ORC-2026-079',
    closedDate: '2026-09-08',
    clientName: 'Mecatec Soluções Industriais',
    clientPhone: '(11) 99123-8877',
    clientEmail: 'roberto@mecatecind.com.br',
    totalPieces: 10,
    items: [
      {
        name: 'Garras Mecânicas para Manipulador Robótico',
        quantity: 10,
        technology: 'FDM (Filamento)',
        materialName: 'PETG XT Branco',
        materialType: 'PETG',
        weightGrams: 85,
        unitPrice: 58.0,
        totalPrice: 580.0,
        rawCost: 168.0,
        netProfit: 412.0,
      },
    ],
    subtotal: 580.0,
    discountAmount: 0,
    shippingCost: 40.0,
    finalTotal: 620.0,
    productionCost: 168.0,
    netProfit: 412.0,
    profitMarginPercent: 66.5,
    paymentMethod: 'Cartão de Crédito (3x)',
    status: 'delivered',
    notes: 'Entrega realizada via motoboy express com nota fiscal.',
    filamentDeducted: true,
  },
  {
    id: 'sale-003',
    quoteNumber: 'ORC-2026-083',
    closedDate: '2026-09-14',
    clientName: 'Studio Arch Design - Camila Rocha',
    clientPhone: '(19) 99344-1122',
    clientEmail: 'camila@archdesign.com.br',
    totalPieces: 3,
    items: [
      {
        name: 'Maquete Volumétrica Edifício Horizon 1:200',
        quantity: 3,
        technology: 'FDM (Filamento)',
        materialName: 'PLA Premium Preto Ônix',
        materialType: 'PLA',
        weightGrams: 190,
        unitPrice: 135.0,
        totalPrice: 405.0,
        rawCost: 118.0,
        netProfit: 287.0,
      },
    ],
    subtotal: 405.0,
    discountAmount: 25.0,
    shippingCost: 0,
    finalTotal: 380.0,
    productionCost: 118.0,
    netProfit: 262.0,
    profitMarginPercent: 68.9,
    paymentMethod: 'PIX (50% sinal + 50% entrega)',
    status: 'producing',
    notes: 'Em impressão na Bambu Lab A1 Combo. Previsão de término amanhã às 16h.',
    filamentDeducted: true,
  },
  {
    id: 'sale-004',
    quoteNumber: 'ORC-2026-062',
    closedDate: '2026-08-20',
    clientName: 'DroneTech Brasil',
    clientPhone: '(11) 97766-3322',
    clientEmail: 'contato@dronetech.com.br',
    totalPieces: 8,
    items: [
      {
        name: 'Protetores de Hélice & Suporte de Antena',
        quantity: 8,
        technology: 'FDM (Filamento)',
        materialName: 'TPU Flexível 95A Laranja Sunset',
        materialType: 'TPU',
        weightGrams: 45,
        unitPrice: 42.0,
        totalPrice: 336.0,
        rawCost: 89.0,
        netProfit: 247.0,
      },
    ],
    subtotal: 336.0,
    discountAmount: 0,
    shippingCost: 24.0,
    finalTotal: 360.0,
    productionCost: 89.0,
    netProfit: 247.0,
    profitMarginPercent: 68.6,
    paymentMethod: 'PIX (Chave Instantânea)',
    status: 'delivered',
    notes: 'Material flexível TPU 95A absorveu os impactos conforme esperado pelo cliente.',
    filamentDeducted: true,
  },
  {
    id: 'sale-005',
    quoteNumber: 'ORC-2026-048',
    closedDate: '2026-07-28',
    clientName: 'Automotiva Prime - Peças Especiais',
    clientPhone: '(11) 98877-4433',
    clientEmail: 'compras@autoprime.com.br',
    totalPieces: 4,
    items: [
      {
        name: 'Duto de Admissão & Caixa de Fusíveis Custom',
        quantity: 4,
        technology: 'FDM (Filamento)',
        materialName: 'ABS Industrial Cinza Chumbo',
        materialType: 'ABS',
        weightGrams: 210,
        unitPrice: 165.0,
        totalPrice: 660.0,
        rawCost: 185.0,
        netProfit: 475.0,
      },
    ],
    subtotal: 660.0,
    discountAmount: 30.0,
    shippingCost: 35.0,
    finalTotal: 665.0,
    productionCost: 185.0,
    netProfit: 445.0,
    profitMarginPercent: 66.9,
    paymentMethod: 'Boleto Bancário (14 dias)',
    status: 'delivered',
    notes: 'Peças em ABS resistente a alta temperatura no cofre do motor.',
    filamentDeducted: true,
  },
  {
    id: 'sale-006',
    quoteNumber: 'ORC-2026-031',
    closedDate: '2026-06-18',
    clientName: 'Agência Criativa Voxel',
    clientPhone: '(21) 99882-1100',
    clientEmail: 'voxel@agenciavoxel.com',
    totalPieces: 15,
    items: [
      {
        name: 'Troféus Geométricos para Evento Corporativo',
        quantity: 15,
        technology: 'FDM (Filamento)',
        materialName: 'PLA Premium Preto Ônix',
        materialType: 'PLA',
        weightGrams: 65,
        unitPrice: 48.0,
        totalPrice: 720.0,
        rawCost: 165.0,
        netProfit: 555.0,
      },
    ],
    subtotal: 720.0,
    discountAmount: 50.0,
    shippingCost: 45.0,
    finalTotal: 715.0,
    productionCost: 165.0,
    netProfit: 505.0,
    profitMarginPercent: 70.6,
    paymentMethod: 'PIX (Chave Instantânea)',
    status: 'delivered',
    notes: 'Lote entregue com acabamento premium e gravação em baixo relevo.',
    filamentDeducted: true,
  },
];

export const defaultClients: ClientRecord[] = [
  {
    id: 'cli-001',
    name: 'Eng. Roberto Albuquerque',
    companyName: 'Mecatec Soluções Industriais',
    document: '29.384.192/0001-05',
    phone: '(11) 99123-8877',
    email: 'roberto@mecatecind.com.br',
    address: 'Rua das Indústrias, 450 - Distrito Industrial, Campinas - SP',
    notes: 'Cliente corporativo recorrente. Sempre solicita materiais técnicos de engenharia (PETG, ABS e Nylon). Tolerância dimensional rigorosa (±0.15mm). Prefere entrega expressa com nota fiscal.',
    tags: ['B2B', 'Industrial', 'Recorrente', 'VIP'],
    createdAt: '2026-06-15',
    history: [
      {
        id: 'hist-001-1',
        quoteNumber: 'ORC-2026-084',
        date: '2026-09-15',
        itemCount: 3,
        totalPieces: 9,
        totalValue: 712.5,
        status: 'quoted',
        summary: 'Gabinete IoT (2x), Engrenagem Z18 (4x), Manípulo M6 (3x)',
      },
      {
        id: 'hist-001-2',
        quoteNumber: 'ORC-2026-079',
        date: '2026-09-08',
        itemCount: 1,
        totalPieces: 10,
        totalValue: 620.0,
        status: 'closed',
        summary: 'Garras Mecânicas para Manipulador Robótico (10x)',
      },
      {
        id: 'hist-001-3',
        quoteNumber: 'ORC-2026-055',
        date: '2026-08-05',
        itemCount: 2,
        totalPieces: 5,
        totalValue: 380.0,
        status: 'closed',
        summary: 'Flanges de Acoplamento em ABS Industrial e Buchas',
      },
    ],
    customDiscountPercent: 5,
  },
  {
    id: 'cli-002',
    name: 'Camila Rocha',
    companyName: 'Studio Arch Design',
    document: '18.291.440/0001-80',
    phone: '(19) 99344-1122',
    email: 'camila@archdesign.com.br',
    address: 'Av. Norte-Sul, 1200 - Cambuí, Campinas - SP',
    notes: 'Desenvolve maquetes volumétricas de edifícios e protótipos decorativos. Prioriza acabamento visual fino (PLA Premium e alturas de camada 0.12 - 0.16mm).',
    tags: ['Arquitetura', 'Design', 'Maquetes', 'Recorrente'],
    createdAt: '2026-07-10',
    history: [
      {
        id: 'hist-002-1',
        quoteNumber: 'ORC-2026-083',
        date: '2026-09-14',
        itemCount: 1,
        totalPieces: 3,
        totalValue: 380.0,
        status: 'closed',
        summary: 'Maquete Volumétrica Edifício Horizon 1:200 (3x)',
      },
      {
        id: 'hist-002-2',
        quoteNumber: 'ORC-2026-068',
        date: '2026-08-28',
        itemCount: 2,
        totalPieces: 4,
        totalValue: 290.0,
        status: 'closed',
        summary: 'Luminária Modular Paramétrica e Suporte de Parede',
      },
    ],
  },
  {
    id: 'cli-003',
    name: 'Leonardo Prado',
    companyName: 'DroneTech Brasil',
    document: '34.551.902/0001-14',
    phone: '(11) 97766-3322',
    email: 'contato@dronetech.com.br',
    address: 'Rua Funchal, 280 - Vila Olímpia, São Paulo - SP',
    notes: 'Peças funcionais para drones de corrida e inspeção aérea. Alto consumo de TPU Flexível 95A e filamento com fibra de carbono. Precisa de envio rápido via Sedex.',
    tags: ['Drones', 'Flexível', 'TPU', 'Recorrente'],
    createdAt: '2026-08-01',
    history: [
      {
        id: 'hist-003-1',
        quoteNumber: 'ORC-2026-062',
        date: '2026-08-20',
        itemCount: 1,
        totalPieces: 8,
        totalValue: 360.0,
        status: 'closed',
        summary: 'Protetores de Hélice & Suporte de Antena em TPU 95A (8x)',
      },
      {
        id: 'hist-003-2',
        quoteNumber: 'ORC-2026-041',
        date: '2026-08-02',
        itemCount: 1,
        totalPieces: 4,
        totalValue: 220.0,
        status: 'closed',
        summary: 'Suportes de Câmera de Ação Angulados 30° em TPU',
      },
    ],
  },
  {
    id: 'cli-004',
    name: 'Dr. Marcelo Fontes',
    companyName: 'OdontoTech & Próteses 3D',
    document: '08.411.233/0001-90',
    phone: '(11) 98111-4455',
    email: 'marcelo@odontotech3d.com.br',
    address: 'Av. Paulista, 1800 - Bela Vista, São Paulo - SP',
    notes: 'Trabalha com guias cirúrgicos, modelos de arcada e protótipos de turbina em Resina 405nm. Exige cura UV e lavagem ultrassônica impecável.',
    tags: ['Resina SLA', 'Odonto', 'Alta Precisão', 'VIP'],
    createdAt: '2026-07-22',
    history: [
      {
        id: 'hist-004-1',
        quoteNumber: 'ORC-2026-081',
        date: '2026-09-02',
        itemCount: 1,
        totalPieces: 6,
        totalValue: 458.0,
        status: 'closed',
        summary: 'Guia Cirúrgico Prototipado & Suporte de Turbina em Resina (6x)',
      },
      {
        id: 'hist-004-2',
        quoteNumber: 'ORC-2026-072',
        date: '2026-08-19',
        itemCount: 2,
        totalPieces: 8,
        totalValue: 540.0,
        status: 'closed',
        summary: 'Modelos de Estudo Odontológico e Casquetes de Alinhador',
      },
    ],
  },
  {
    id: 'cli-005',
    name: 'Beatriz Lima',
    companyName: 'Nexo Brindes Corporativos',
    document: '41.209.771/0001-33',
    phone: '(11) 96555-9090',
    email: 'beatriz@nexobrindes.com.br',
    address: 'Rua Augusta, 890 - Consolação, São Paulo - SP',
    notes: 'Pedidos em lotes de 15 a 50 unidades. Troféus comemorativos, chaveiros e suportes de mesa com gravação personalizada.',
    tags: ['Brindes', 'Lotes Grandes', 'Corporativo'],
    createdAt: '2026-08-10',
    history: [
      {
        id: 'hist-005-1',
        quoteNumber: 'ORC-2026-048',
        date: '2026-08-15',
        itemCount: 1,
        totalPieces: 15,
        totalValue: 715.0,
        status: 'closed',
        summary: 'Troféus Geométricos para Evento Corporativo (15x)',
      },
    ],
  },
];



